### PR TITLE
Updates and added Notification

### PR DESCRIPTION
**Pull request by hot33331**
Updated Libraries
Added missing artwork
Added example notifications for macOS and Windows

### CODE REVIEW

**Comment by Rjvs** [comment]
@hot33331 this worked for me the first time I build and ran it notifications were displayed as expected on macOS 12.2.1 but on subsequent runs the notifications silently fail.  I presume that it is a macOS issue (there was no "allow notifications" notification) but any suggestions?

**Comment by hot33331** [comment]
Good question. Quite some time since I made this. You can however go to system preferences and allow notifications there, I think. But most certainly a permission issue. Maybe xamarin essentials could fix this. Don't recall that issue though...

**Comment by Rjvs** [comment]
The trick is to copy a build into Applications, so it will appear in the notification settings list and you can then allow notifications.  It appears that you can then build and run from anywhere so long as you maintain the same bundle ID.

**Comment by hot33331** [comment]
So anything blocking this merge here @Rjvs @krdmllr ?

**Comment by Rjvs** [comment]
It's good for me.

**Comment by krdmllr** [comment]
Honestly just forgot about this, thanks for the work!

**Pull request merged**
